---
title: "Untitled"
output:
  word_document: default
  html_document: default
---

```{r include=FALSE}
library(knitr)
opts_chunk$set(list(echo = FALSE, eval = FALSE))

```
Untitled
As a teacher, I have experienced changes in the role of educators and students in the learning process. When I started my career in higher education teaching in 2003, the classroom was teacher-centered. Students needed to attendclasses, listen, understand and reproduce the subject in evaluative activities.
In these current disruptive times, even in an underdeveloped country like Brazil, we have gone through a revolution in access to technology and the consumption of information, resulting in the change instudent behavior Lectures and PowerPoint presentations are not enough to sustain the engagement of students in the classroom. These changes have been a motivation for me to seek to improve my skillsas a teacher, with the aim of adapting to an educational paradigm in which students are the protagonists.
In Brazil, students and teachers are still adapting to the idea that we can work together, and that learning is a collaborative process. Sincethis context, I have been striving to transform myself from teacher to tutor, reducing  distances I am trying to become a curator or mentor, who assists students in their academic journey to transform information into knowledge and develop skills to act in society, contributing to a better world.
Content is no longer the main element of the teaching-learning relationship; and information is ubiquitous, despite inequality in terms of access and quality. There are still inequities in access to technological resources, but emergency remote education in the SARS-CoV-2 pandemic has opened the need to universalize access to digital information. My goal as a teacher is to help students transform data and in training intoapplied knowledge and develop critical thinking and social responsibility as citizens and professionals. The approaches I have implemented are designed for practical activities and diverse discussion. For this, I have used different pedagogical approaches in the classroom, mainly based on hybrid learning, Project and Problem-Based Learning, inverted classroom and peer review.
Motivating students to question the processes (within the still contentious courses), envision methodological paths, analyze problems and propose solutions is always a challenge. To increase student engagement, I have been developing problem solving projects focused on real social issues as the essentialart of the courses. Students are motivated when the objectives of the projects are clear, however intangible, and like to have the opportunity to decide on the contextualization of the social issue under discussion.
The evaluation is the educational activitythat intrigues me the most and motivates me to seek improvement as a teacher. Bringing a flexible agenda to the classroom, focused on the needs of students, is even more challenging in the face of the need to quantify academic performance. I think deciding how to evaluate learning is one of the most provocative tasks I face on a daily basis.
Teaching applied computational tools is another daily challenge. Labs can be difficult if students are not interested. I haveusad the reversed lessons with intensive digital teaching resources such as interactive tutorials, videos and forums for discussion to promote this subject. The laboratories became a space to solve doubts and discuss the implication of theco-mputation alseumimplementations they carried out. It's not perfect, but in my experience, the results of this approach are much better than exhibition classes and hands-on work, as students can learn at an individual pace.
The classroom needs to bea place of diversity. Students should feel comfortable expressing themselves and accepting themselves for who they are, respecting each other's inherent skills, developing skills and building a good environment to share and learn.
I learnedthat collaborative work is the best way to engage students. I intend to continue developing teaching skills to bring joy, warmth and viable challenges to the classroom in order to inspire and motivate students. Making thetudantes acquire knowledge, collaborate, develop critical thinking and mature as citizens is a professional goal and a personal passion. Education is the only way to a fairer and fairer world.
Manifesto for a better world
"(...) seres human beings are social beings by nature and that he who is not able to live in society or who feels self-ressure, or is a beast, or a God."  Aristotle (384-322 a.C.)
THE ROLE OF THE URBAN STRUCTURE IN TIMES OF COVID-19
According to Ratzel, the concept of territory is characterized by the process of construction andtransformation of the geographical space and by the imposition of power, idealized through the conceptionof a State that transcends purely legal aspects and is structured on the relations between space and society that inhabits it. However, the process of building territoriality is not always related to space; may be related to networks that interconnect agents and flows, presenting important stupego variations and establishing itself in natural, political, cultural, social, economic, military relations, among others. If we think of the contemporary world, the concept of territoryis present in most human relations, distinguishing individuals, processes and ideals according to the collective they represent. In the mid-1970s, Yi-Fu Tuan forged the terms topophilia and topophobia in his work, establishing thedifficult conceptual evolution between space and place.
Unlike the concept of territory, which relates to networks of power, the place is the individual interpretation of geographical location from the perspective scans of human perception, its spatial representation, andsocial and cultural re-lações. This concept is loaded with affections and disaffections, established under strong subjectivity and differentiation of the individual in the geographical space. The place is related to the feelings we build in relation to that space where we go through individual and collective experiences. Being in some places promotes us joy, identity and esteem – Topofilia. In others, revulsion and fear – Topophobia. Everyone perceives, means and idealizes the place where he lives. Home is different from home, buteco is different from bar and alley is different from platter. Since the first records of the evolutionary trajectory of the human species, the need for interaction between people is evidenced. We are, before any imaginary, social beings. Territory and place complement each other in relation to the ability to understand space as an essential element to the conformation of social relations between individuals. Territory and place differentiate human beings through collective interactions, based on power, and individual perceptions. These two concepts underlie the construction of the contemporary human habitat: the city. In the city, both urban functions and the geographical space built and transformed represent those who inhabit it. The first settlements humain the known, according to some historians, are located in ancient Mesopotamia and emerged under the rule of the Sumeans about 5,500 years ago. In turn, the best-known ancient cities today were built during the Roman Empire. Sumeriancities such as Roman cities had common genesis: the need for human interactions related to exchanges of goods, religious and cultural practices and the need for centralized administration and fortification. In the central area ofthe city s were installed the forum, the market and the church, differentiating the urban space according to its purpose and importance.
The emergence of cities is also marked by the first records of specialization of work and the accumulation capacity of excedente. In this context, the urban way of life is consolidated, definitively marking economic, social, technological and ideological relations. The differentiation of space, added to the differentiation between citizens according to their competence and ability to acumular wealth, synthesizes the human construction of the concept of territory and power relations. The perception of individuals about themselves and others depends on a social imaginary. As an example, the peripheral regions of cities are less important in society, as well as their inhabitants. In the urban context, humanity has developed and consolidated the contemporary way of life, sustained by the availability of natural resources and by social and economic relations, intrinsicallyunequal. By 2020, about 50% of the global population lives in urban areas and 86% of Brazilians live in cities. In addition, we have experienced increasingly intense urbanization rates. The need for human interaction marked eras and was responsible fordiffering in innovations throughout our history. Overcoming the impedances promoted by distance has been an important trigger for technological conceptions that have changed our lives for a long time. Different transport technologies have been consolidated up to the currentones, but the advent of steam engines and, later, combustion and electric engines, were the great innovations that allowed the increase of speed in people's displacements. Railroads began to be developed in the19th century, and lasted to the present day, without significant structural changes. This technology was responsible for the expansion of the occupation of the interior areas of different countries and to this day is a very suitable means of transport for regional and urban connections. Throughout the 20th century, we witnessed the advent and popularization of automobiles, civil aviation and high-speed trains. It has become possible to move people by air with a speed of more than 1000 km/h  and land up to 300 km/h. Speed, always seductive, still promotes challenges and innovation, such as the design of the Hyperloop, aiming, increasingly, to reduce distances. In addition to regional expansion, transport has delineated cities around the world, withgreater speed in connections between people and for individuals to save energy, because we don't have to walk to reach our destinations. Cars quickly became a status symbol and began to dominate the cities. By the end of the 1910s, citizens, who had been living for some time with different animal traction vehicles, such as carriages and carriages, were accustomed to sharing urban space, favoring interaction, which was previously predominant. The diffusion of automobiles isa very disruptive phenomenon and, in a very short time, the automobiles already governed the occupation of the roads in the cities. As a symbol of this change, the term "jaywalking", conceived by Americans who referred to pedestrians crossing some road outside controlled intersections; a pejorative term that places the pedestrian in a lower position than cars, stands out. This term resists time, as well as the hegemony of automobiles over Brazilian cities, in contrast to the naturally imitated speedof men and animals when moving around. As a consequence of the enchantment promoted by automobiles and speed, urban planners idealized and encouraged the construction of specialized cities, with areas dedicated to specific functions, such as hospital and industrial areas. This line of thinking of urbanism conceived and reshaped the cities so that the automobile would become a protagonist in the urban way of life. The cities were adequate to the speed of motor vehicles (60 km/h), possibilitando the urban occupation in an increasingly beachy and less dense way, but dependent on motorization for access to basic functions, such as work, health and the acquisition of food. Some cities, such as Belo Horizonte, whosegenesis occurred at the beginning of the last century, had projects in which displacements were favored to the detriment of the characteristics of the natural site, with the design of orthogonal road networks and overlapping natural watercourses. These guidelines for the construction of cities were seen, for a few decades, as synonymous with modernity and progress.
Also throughout the twentieth century and in the Brazilian context only at the end of this period, we conceived a model of production and consumption on a global scale, enabling stages dand production, of the same product, geographically separated by more than 10,000 kilometers. For viable, we understand the ability to generate remuneration of the capital of investors, far from the value promoted by manufacturing and attentive to the dynamism of the market financeiro, disregarding the demands of natural and social resources for this model to sustain itself. The cohesion of functions promoted by the urban context and by regional networks of production and consumption determines the contemporary way of life. Each individual builds his perception of place and adapts to the territoriality of the spaces where he circulates and adapts to diversities. However, this way of life is threatened by structural changes, in different dimensions, that permeate our existence without stopping to understand, criticize, mitigate them, refute them or accept them. Part of these changes is made possible by technological revolutions that allow interactions between the physical, biological and virtual means, making the distinction between the human and thetural, between the urban and the rural, increasingly cloudy.
This process is called the Fourth Industrial Revolution, and leads us not to rely on geographical boundaries so that there are interactions between people, in addition to the replacement of differentfunctions by "intelligent" machines. With the most contemporary possibilities of work on demand, telework and virtual communication, the relativization of geographic space becomes reality and we have the feeling of always being connected, meeting an intrinsic desire ofthe human being. On the other hand, the natural environment manifests itself in an intense way and contrary to the speed promoted by the motorization of displacements and the digitization of communication. We are experiencing extreme weather events that compromise both the quality of life of people and the enrichment of the holders of capital. Catastrophic rains and the warming of some areas of the planet are phenomena already frequent in our daily lives. Earlier this year we came across a new and immediate challengefrom human relations with the natural environment: the pandemic caused by the spread of the new coronavirus on a global scale. This phenomenon has deprived and deprived the different individuals of their physical freedom to come and go. Different concepts such as social development, social isolation and lockdown invaded our lives and resulted in the reduction of displacements and human interaction, at different intensities and scales. It is an extreme phenomenon that radically changes our way of life. It issaid that these changes are transitory and that we will soon return to "normality"; others claim that distancing is unnecessary and brings more harm than benefits to society.
But in the face of the unknown behavior of SARS-CoV-2and its ephemes about Homo Sapiens, most nations chose to preserve human life to the detriment of other values that were previously sovereign. These changes occur in the economic structure, in the urban dynamics, in the patterns of consumption, in the direction and intensidad and displacements, in the freedom ofindividuals, in the perception of happiness, in the environment, in the daily prioritizations, in the faith. These are examples of dimensions on which the pandemic has caused a disupand over which we have failed to infer the consequences inthe medium and long term. The changes in society from the COVID-19 pandemic The economic and demographic repercussions of the diffusion of the new coronavirus depend on the weaknesses and vulnerabilities of the current social, economicand geographic model. One of the drawbacks of increasing globalization is the impossibility of stemming the rapid international spread of new diseases. The world is connected on a global scale in the physical and digital media and the spread of the virus is much faster in regions with higher population density and, therefore, this characteristic makes its impact more significant in urban communities. Economic sacrifices are being needed around the world, changing the dynamics, at least in a transitory way, of the processes of production and accumulation of capital. As we reduce non-essential consumption, we are seeing economies around the world declining. Hospital materials necessary to maintain the lives of individuals affected by the virus are lacking in different nations and the supply of these components, with production centered on a global scale, is disputed by countries holding the capital. Different work activities were limited by social distancing. Trade and the service sector, still heavily dependent on human capital, succumbed to the closure of physical stores, resulting in reduced compensation for their employees, imposition of vacations during the pandemic and layoffs. Small entrepreneurs and self-employed workers, formais and informal, found themselves without means of producing during social distancing, being forced to terminate their activities definitively. On a global and systemic scale, the values that capital can produce are being compromised by an  insufficiency of effective demand due to the pandemic and the consequent adaptability of the human being. Also due to social distancing, the controversial universal minimum wage returns to the discussion in different countries, evenin those nations the state has positioned itself in such a way as to allow full freedom of citizens, with the argument that the protection network, which in other contexts is public, should be organized individually. However, as access to opportunities is not active equit, many workers are in a situation of vulnerability because they do not obtain enough income for the essential to daily life and, even less, to organize resources for their protection in adverse situations. Even with some community support, access to basic resources for this vulnerable population is still insufficient. In Brazil, the informal workers, who represent more than 40% of the Brazilian population with some occupation, no longer had any social protection network that would have the effects of the assignment of production in situations of unemployment, illness or permanent incapacity to work. During the distancing, the federal government proposed the distribution of resources for the subsistence of this vulnerable population, but access to aid has been compromised by the invisibility of these workers and families. These "citizens" occupy territories necessary for the urban way of life, but are invisible to the formal structure of society. This invisibility has consequences foreveryone, including the taxpayer who understands to benefit from this situation. Intensifying the precarious nature of informal work, there are increasing activities related to the gig economy.
This last concept is part of on-demand work and is characterized by the use of technology for workers to be connected to temporary demands, and become responsible for the management of their own competencies, time and income. A current example of this economic relationship are the motoristas of applications for the transportation of people and deliveries that are available for any income-generating activities, even if precarious, due to the scarcity of jobs in Brazil. Some of these workers resorted to this activitybecause they lost income with distancing. In the context of the pandemic, the home delivery of essential products, such as supermarket items, medicines, ready meals, has become an essential service that allows some citizens tostay at home. For the home delivery of essential consumer goods to happen, an extensive, if not global, production chain is needed that fills the distribution centers and traditional retail with food, toiletries, limpeza and medicines. Despite allowing the maintenance of some production chains and part of the social distancing through home supply, only family groups belonging to more favored extracts and with maintenance of income can benefit from home delivery. This situation increases inequalities in the city and the poor population, already segregated due to spatial and economic attributes, is the one that needs to choose between:adhering to social distancing, without surrender and with risks of compromising family subsistence or dismissal; or running the risk of contamination in order to maintain work activity. In the latter case, animportant part of these workers still needs to exercise displacement scanning for transportation in crowded vehicles, generating the agglomeration of unwanted people in the containment of the diffusion of coronavirus. Despite all the technology and automation of services made possible by the Internet, artificial intelligence and machine learning,the inda we need to have truckers transporting goods on the roads, employees working in assortment centers, motorcycle drivers performing the delivery in homes and drivers driving buses through the cities. The demand for transport, whichenables connectivity between urban functions, is more evident to society due to changes in the means of displacement and forms of consumption. This demand is a consequence of the distances between housing and labor, production and consumo, resulting from the territorial and economic choices that we have made throughout history. The advance of COVID-19 exalts the inequalities of cities of class, gender and race. To meet the need for interaction and maintain some alignment with cotidia life, a portion of our society has experienced the full digitization of the environment of work, study and social coexistence.
The city was divided into new territories, the most and the least privileged, due to its professional activity and the new conditions of access to goods and services. Not everyone can replace work with telework due to: inequalities in access to equipment and connections to digital networks; scarcity of financial resources to demand essential services and products through technology; and because they need to maintain displacement due to economic constraints, market pressure or work in essential activities. In addition to inequalities in access to technology for distance education, an important part of students does not have the maturity and autonomy to benefit from exclusively digital classes, such as children in early childhood education and in the first cycle of elementary school, because social interaction is still fundamental for the formation of the individual. Healthand educational institutions, designed to cover the entire population, become another instrument of segregation when only people who have means of access to the Internet can protect themselves through distancing. In general, theportunits of work, education, housing, health care, leisure, among others, physical or digital, are not distributed to all people equally, not even in more developed countries, and the structure of cities has significantcontribution to maintaining this inequality.
Segregation and unsustainability: cities in time of COVID-19 To understand the changes that the pandemic has brought to people's lives, we need to resume the concepts thatunderlie the urban structure and the relationships we establish with space. The main function of cities is, undoubtedly, human interaction, where social distancing becomes antagonistic and controversial, but necessary, driving people away and transforming urban space. The process of construction of the urban way of life, in intraurban and long-distance scales, crossed the limits of environmental, social and economic efficiency. These three dimensions are fundamental to the composition of the concept of sustainability and are compromisedby the current way of life. We consume natural resources above the planet's generation and regeneration capacity. We ignore an important part of citizens in the design and implementation of public policies. We conceive self-sustaining economic practices, centered on the individual, with the expectation of immediate benefits based on the merit of each one and not on the differentiation of opportunities and the need for everyone to have access to the essentialto human life and dignity in the medium and long term. With the mia pandemic, the fast connection between citizens promoted by the urban structure oriented to the automobile lost space for flows of consumer goods - supply processes and home deliveries - and for the even more immediate connections made possible by thete cnologia. But these changes are not valid for all citizens, especially in the urban context. Physical distances remain the same, as COVID-19 has not been able to change the laws of physics. But the perception of distancing is quite differentand the inhabitants of the same city are directly related to the place where we live and perform our activities and income conditions. Those who have the physical and financial possibility of moving with greater speed or not reside in the peripheries,and stand close to health equipment, have greater chances of receiving medical care. The less-favored population is more vulnerable, both due to the population density of places of residence - increased transmission rates - and in the face of difficulties in accessing health centers. The public and community spaces of the cities were emptied. That place marked by affective memories, where it is enough to "be", has become only a set of artificial and purposeless constructionsfor human life. Even in a transitory way, the emptying of public space brings a sense of insecurity, impersonality and fear. When the urban space ceases to be a place of well-being and pleasure, new territorialities arise, and can transform it through references that provoke fear, revulsion and, consequently, desire for distancing. In addition to the need for social distancing to contain the spread of the virus, we need to live with the loss of individual and collective identityby moving away between life and urban space. Peripheral communities are characterized by the population living in slums, settlements or precarious regions (in relation to urbanization and access to the city). These communities establish their own territories afterthe gaps left by the public authorities regarding the promotion of public policies directed to their specificities, presenting their own economic, cultural and social identity, great diversity and a high capacity of self-organization for problem solving. They are rich and humanized territories, but usually do not count on financial contributions that should be made available by the public power because they are informal.
The evidence so far indicates that the classes less favoredeconomically in Brazil, mostly living in peripheral communities, are those with higher mortality rates from COVID-19 infections. The geography of contamination and mortality rates is a determining factor in the patterns of diffusion and severity of infections. In the context of the pandemic, the demand for support from the government becomes even greater, mainly due to the assignment of income. These communities have made claims to the rulers of the cities quite clearly: they need sanitary barriers for the "city" to stop invading the "territory". They have organized themselves with social isolation centers for those who need to move away from their families. They have sectorized care through household guardians.  However, they are people invisible to the government and to "citizens", although very representative in population, economic and social terms. As well as workers in the informal economy and the gig economy, which partly makes up the periferic communities, it is more convenient to ignore their existence for the formulation of public policies, but to take advantage of the low immediate social cost they provide for the informality of work, economic relations and public demands. But the price for society of this orientation of public policies prioritizing the formal city, in the medium and long term, is very significant.
A very characteristic socio-spatial conformation process in developing countries is the "favelization" of urban areas. The periferization - called espraiamento quando compulsory - is an urban process analogous to favelization, being characterized by the occupation of peripheral and periurban areas as an alternative to the high prices of real estate in the areas with higher concentration of opportunities, and also by the precarious conditions of housing and essential services. It is worth mentioning that, despite having common elements in relation to socioeconomic, demographic, housing and access to essential services attributes, the favelas and peripheral areas of the city are quite different in relation to access to the city. The urban spread affects population strata at the base of the economic pyramid, distancing them from the functions of the city, generating inequities regarding access to opportunities for work, education, health and leisure, among others. The low accessibility, as a result of both decisions regarding land use in cities and the impedance that displacements promote, is another element of segregation. Composing a negativo cycle, there is a reduction in demand for public transport, intensifying the reduction in revenue from these systems – coming from the fare – already identified in different Brazilian cities before the pandemic.
As a result, there is the suppression of supply, generatingthe important risks of permanent suppression of higher capacity transportation, making it a gap of essential services for society. There is, therefore, the risk of forming a new informal territoriality to meet the demand for transporte. This suppression, coordinated with the spatial concentration of opportunities, will accentuate the inequities in relation to urban accessibility. Positive reflections in times of pandemic COVID has forced people to perform basic functions in a differentway. The form does not necessarily imply changes that bring improvement to cities. The environment only facilitates or hinders how activities are performed, but still exercise our role as providers and consumers of services and activities that are tohuman life, such as housing and food. Most of the food consumed in cities is produced outside it and needs to be transported for it to be available. We need to resort to health care, but in times of pandemic, a medical consultation becomes possible and desirable through virtual means, even for those who have access to the necessary technology. We need access to the educational training of children, young people and adults that takes place, in essence, through exchange, butat this time, some people can only rely on the digital environment for home education. Exception periods such as the current one are potentially positive, even with all negative impacts coming from a pandemic. It is necessary to be open to seeing positive aspects in a global crisis and, when possible, we can consider the pandemic as a time to revisit the individual and collective choices we make and rethink guidelines for managing our habitat. Consumption patterns: Contemporaryconsumerism has played an important role in environmental degradation. Changes in behavior in relation to the consumption of non-essential goods and services is a positive aspect impacted by social distancing. Cancellation of flights, restrictions on movement in cities, both to contain the spread of the virus and due to reduced consumption, has contributed to reductions in fossil fuel consumption. Consequently, different localities, on a global scale, have experiencedsignificant reductions in air, sound and visual pollution. In several parts of India it was possible, for the first time in more than 30 years, it was possible to visualize the Himalayan mountain range due to the reduction of air pollution. The reduction of noisepollution has stimulated birds, mammals and other wild animals to circulate through the cities, blending nature and human habitat. Reducing greenhouse gas emissions positively impacts accelerated global warming rates. Different itiesdegraded by tourism are managing to recover in the face of the absence of consumers of this service. Urban structure: Barcelona, London, Paris and different examples around the world form a set of cities that are remodeling the urban space so that there is prioritization of pedestrians and cyclists, at a time of intense reduction in the use of public transport. Economic relations: The situation of thousands of people living conditions of precarious work and vulnerabilityis less invisible with the pandemic. For the first time in history, the price of oil in the international market reached negative values, compromising an entire network of capital gains dependent on this natural resource. Individual aspects: we discovered new pleasurable activities that would not have been explored in our routine. We found that we are more resilient than we thought and that we can adapt to very adverse scenarios.
We experience a slowdown in the daily rhythm, which allows usto have the right to contemplate, to reflect, to change. We value as never before professionals not so valued, such as health professionals, delivery men, garbage men, teachers and truckers. Discussion of the role of technology as a solution to urban problems: we have technology in our favor. The demands of social distancing are a catalyst for the technological changes that are happening. We wear electronic equipment that monitors us in real time; we live with sisthemes and objects built on the basis of artificial intelligence; machines learn; cities are intelligent. However, no technological advances have so far been able to overcome the cognitive capacity of human beings. It is not known how or when thehuman species has become "intelligent", but it is understood only we have a communication capacity that allows us to imagine and transmit information about immaterial entities, unlike other animals. There are no intelligence systems or intelligent cities that can make decisions in disruptive scenarios aimed at adaptation, because the "intelligence" of machines is only the ability to learn from what is known, with predetermined relationships. Only man has the capacity to creater, innovate and design solutions in adverse contexts. We need to reflect on the role of technology in our lives. Thus, the implementation of technology solutions are not, in themselves, paths for the promotion of quality of life and for the reduction ofequality. Smart cities, as an example, could become lifeless spaces, where autonomous vehicles are priorities over pedestrians; where civic engagement is reduced to requesting services through applications; where public policiesand agents use algorithms to justify racist practices; and where governments and businesses oversee public space to control behavior. Urban problems are not technological problems. Technological solutions are very welcome to make changesin the social structure of communities, but should be seen as a means and not as the final goal, because technology-oriented urban solutions tend to present innate limitations and the digitization of society can strengthen specific ways of exercising power and authority and, consequently, the increase in inequities. What does it have to change? Prior to the process of specialising urban areas, a variety of functions were available at walking or cycling distances from citizens' homes. Today, the concept of self-sufficiency predominates in decisions about housing and economic and social relations.
We seek to live in self-sufficient units, with the possibility of storing food, entertainment,learning and communication. Before, going shopping was an interactive process, through which people knew each other, experienced common places, performed economic and emotional exchanges and composed communities and territorialities. Today, impersonality is favorable to distancing. Amazon, one of the world's leading electronic retailers, has physical retail points whose concept, related to the future, is based on the possibility of making purchases without any social interaction. We got lost at some point! We organize ourselves for thousands of years in collectives called cities, aiming at mutual benefit, territoriality and belonging to communities, efficiency in production and consumption relations, universality of opportunities and thepotentialization of social interaction and today we value the possibility of reducing social interaction. We need to rethink our cities, valueing humanity, producing development centers driven by knowledge, diversity, curiosage and creativity. The city must once again be a place of building relationships and interactions, before we adapt and social distancing becomes an option. It is important to rethink the distance-speed dichotomy. Speed inhibits the eye, exchanges and social relations. We seek to exercise our functions in society with maximum productivity, for capital and for those who can accumulate wealth, surpassing the ability to do and be, without being able to change time. To be produtive, we need to be faster, and with each increase in speed, we enable greater distances between us.
Social distancing can serve as a trigger for rethinking the concept of productivity of our individual and collective actions, with impacts on sustainability. By experiencing compulsory distancing, associated with the slowdown of the routine, we can reflect on what is relevant or not to our well-being. The relations of production and consumption should also be rethought in connection withthis dichotomy, rethinking the possibilities of local production and consumption, less geographically dispersed, allowing greater interaction between economic actors and less impact on the environment. In the 1960s, Jane Jacobs innocame the discussion andthe urban structure, proposing the breaking of the paradigm of speed and the rethinking of cities as systems in which individuals and groups represent different and essential roles. She proposes that we resume the focus on people and that planning be carriedout on the human scale, deconstructing the idea of development based on separation and specialization of spaces and speed. We have removed space for pedestrians and cyclists to supply the capacity demanded by vehicles.
Planning a city on a human scale is to promote access to opportunities at walking or cycling distances. It is to think of a city appropriate to the urban way of life, but in which displacements are possible at 5 km/h. Walking and cycling, as wellas being pleasant to the body and mind, help reduce environmental degradation and contribute to social interaction and the economy of cities. Active people get sick less and are more productive. This thought has been elaborated in a more contemporary way byauthors such as Jan Gehl, who considers the human scale as the individual and community perception in relation to space. It is related to our perception of belonging to territoriality, with well-being in the places where we perform our functions as citizens. The human scale depends on civic engagement, because the construction of space can only be suitable for a community if everyone is protagonists and behavioral changes oriented to the need to promote meaning to life. The government and trends in the real estate market must understand the demands of each social group and not the other way around. Each city has its own challenges, but it is necessary to remodel spaces with a focus on human interaction, respecting the particularities, customand local beliefs and culture. We need attention to the need for efficient financing, governance and regulatory mechanisms, important for the effectiveness of actions in a collective. Global experience shows that poorly connected and sometimes underutilized urban areas can be remodeled to promote a variety of uses, allowing greater social inclusion, civic participation, recreation, safety and sense of belonging. When well designed and managed, public spaces are also inst rumentos for the promotionof environmental sustainability, efficiency of mobility systems, improvement of health care, meeting the demands of society in a more equitable way. They can add commercial value and economic benefits to each city, as well as stimulate tourism and its competitiveness. The need to prioritize social capital in cities has become more evident in concurrency with the 4th industrial revolution, through which technological increases have proposed importantchanges in people's way of life and also in the way human phenomena are evaluated and investigated. Accessibility-oriented planning can be an important tool to promote the necessary changesin this problem of disreachment. It is not possible to think of the city only on the basis of past phenomena. We must organize ourselves so that we can be assertive in the proposition of public interventions with a common future objective, guiding the construction of a "newnorm l" more aligned with human needs.
We cannot predict what will happen, but we can, along the way, fill the conceptual, procedural and technological gaps that arise between the now and the "ideal" city. We need to take advantage of this stationary moment caused by the pandemic to reflect on how we can act in the constitution of more humane cities. Cities should be able to provide basic needs to all citizens, such as food, shelter and security, allowingthe development of public and private agents, limited by the capacity to renew the environment. Cities must be social constructions that enable purpose to human life in an inclusive and sustainable way. Each city should be a place, where we feel good, happy and healthy, with pleasant memories and with the desire to stay. It must be a territory to which we belong; be part and lack.
Where my heart beats
Dream that one dreams only, it's just a dream that one dreams of. Dream that one dreams together is reality!  Raul Seixas
This section deserves a unique document. It is the most delicious section of this memorial! Despite all its importance, I'll just make a timeline with some photos to warm the heart! Words are insufficient...
❤️Maio 2001 - We started dating! 
❤️September 2001 - We got engaged! 
❤️December 2002 - We live together! 
❤️July 2005 - We're married! 
❤️November 2009 - Sofia's arrival in our lives! 
❤️December 2012 - John's arrival in our lives! 
❤️May 2021 - I follow the happiest woman, mother, teacher, researcher and citizen in the world!
When a mother is born, a new opportunity to learn is born. Experiencing discoveries, cognitive development, learning a human being, is magical! I don't think there are enough training theory or actions in the world to overcome how much I have learned about learning and human behavior. ❤️Sofia and John❤️, THANK YOU VERY MUCH for the opportunity to accompany you! Thank you, Patrick❣️, for the possibility of consolidar a beautiful family with you!
❤️I love you! ❤️
I was born in 1979 (@ref(fig:reta-baby-1)), in a middle-class family typical of the time that fought to conquer social ascension through education. My mother, Maria Lúcia Magalhães de Oliveira, is a technique in chemistry and, when pregnant with me, graduated in Mechanical Engineering at CEFET-MG. I can say that my relationship with this institution began when I was still being pregnant and that our paths reconnected later. My father, Odimar José de Oliveira, is a business administrator (@ref(fig:pais)). I have no sisters (of blood), but throughout life I have accumulated great friends whose fraternal love is so great, or even greater, than that among siblings born to ordinary parents. Do notyou list these friends nominally, because I run the risk of leaving someone out, but know that they live in mine ❤ .
My parents worked full-time and I was under the care of my grandmother Gecy de Oliveira Magalhães (@ref(fig:gecy)) andhome employees. My grandmother was one of the most important people in building my character, my personality and my essence. Unfortunately it is no longer on this earthly plane, but it sure fills a huge piece of my heart. In that hollowera education was an effective path to access to opportunities, to reduce the distances between today and a better future. My parents struggled to pay private school fees, complementary language courses, typing, arts. I studied at St. Doroteia High School . In that context, it was the best formal education that parents could provide to their children. Still considering education as an instrument of transformation, my parents made it possible for me to become proficientin English language and in typing .
I have always been a dedicated student concerned with academic performance, without, however, considering that academic success in the traditional education system would reveal something about me or put me in a different position from my coleges and friends. Entretanto, until early adolescence, I was always quite introspective and shy.
From 4 to 16 years i've naided, i've born.... 🏊🏊🏊🏊 and I studied, and the 📚 repetition of words is a proxy for the intensity of these activities in my routine. Throughout adolescence FUi discovering new ways to relate to people, which was very positive also in the paths I built for professional life.
When I was 16, I ventured into my first international experience. I lived as a high school student for 6 monthsin the United States, Idaho . It was a wonderful experience. In the mid-1990s, the internet was a technological advent available only in academic centers and phone calls had prohibitive prices! Our main means of communication was conventional mail and the exchange of letters.
Professional choices and academic paths
The world of work has always been present in my life. Whether it's because of the professional activities that my parents performed, i.e. by my will, from adolescence on, to be independent. The work proved to be a natural part of my life very early, but not out of necessity. My family's financial condition was decisive in my access to education and, if it were my desire, I could leave to enter the world of work later. However, despite my insecurity about my skills, I assumed the vocation and as soon as I returned from the exchange in the USA, I began teaching English.
Graduation
Choosing the profession is always a challenge, especially when we are very young and associate the perspective of work with the disciplines we take throughout basic education. In fact, I already had a profession when I had to fill out the application form for the vestibular with my university course options.
For many years I was passionate about biology, more specifically zoology, but could not dissect an animal in the laboratory. However, in high school, I fell in love with chemistry and physics. I've been thinking  about going to basic physics in higher education. However, and also due to the influence of my mother's professional choices, I considered engineering as the most professional path aligned with my vocation. Today I believe that everyonehas the vocation to any areas of knowledge. All we have to do is be motivated.
Among engineering, my first option would be to study chemical engineering; very intuitive. However, when I entered university in 1997, there wasan economic recession that greatly limited job opportunities for engineers. Thus, my line of thought was to choose the university course according to employability or possibility to practice the profession informally. Among the various options in engineering, civil engineering seemed more versatile so that I could eventually have a source of income, even if informal.
And so it was. I took entrance exams for civil engineering and was approved at FUMEC, PUCMinas and UFMG. Fortunately, when Approved in the three institutions, I was able to choose and started, in February 1997, the civil engineering course at UFMG.
Institute of exact sciences and topography laboratories have been my home for two years, which consolidate the "basic cycle" of engineering. During this periodI could not explore engineering as a profession. They were subjects not applied and I continued to exercise my professional activity as an English teacher. In 1997 I got a place in a language school and,for the first time, I had access to a qualification course to practice foreign language teaching. It was a differential at that moment in my life, because I realized that, although I loved teaching, there was also a lot of technique and processes that would potentially improve my classes.
Segui teaching at this school for a year. After this period, I chose to teach private and group classes and managed to maintain this activity as my profession and source of income until the middle of the undergraduate course. In the sixth period, I decided to invest in myengineering training and do an internship in a construction company, to explore the paths that civil engineering made possible. I did an internship in a construction budget sector and i couldn't fulfill my six-month contract. I asked for a shutdown in thefifth month, because I could not devote myself to doing the same activities daily during the month.
As my day is only 24 hours (sometimes I still forget it), I had to reduce my load of English classes and, in the seventh period, I got a place as a scientific initiation fellow. The project was entitled "Residential Mobility and Transport System in the Metropolitan Region of Belo Horizonte" and was developed in the Department of Transport Engineering and Geotechnics under the guidance of Professor David José Ahouagi Vaz de Magalhães.
I've made a lot of use of my academic life in higher education. I explored some of the opportunities offered by the public university, getting involved in different activities. I participated in different instances of the studentrepresentation: (i) I composed different managements of the Student Guild of Civil Engineering; (ii) I was involved in projects of the Academic Directory of Engineering; (iii) I represented the student body in departmental meetings and in other collegiate scans; (iv) I learned to mand position in an adverse way the common sense in the collegiate bodies to bring the student perspective to the discussion; (v) I learned how university academic departments work behind the scenes.
In addition to studying Civil Engineering, in the eighth period of this course, already formally collaborating with the scientific initiation project, I decided to try another undergraduate course. Intuitively I thought in letters, but Understood that there would be no directcontribution to my professional training. I decided to study foreign trade and took an entrance exam for a private college called UNA. I was approved and studied at night a semester of Foreign Trade. I did not adapt to the institution, the course and the textand ended up attending only the first semester.
On January 8, 2002, I took a degree as a Civil Engineer at UFMG (@ref (fig:forma)). 
________________________________________
Postgraduate and professional and faculty experiences before CEFET-MG
At the end of the engineering course, I have nodoubt that I would need to deepen my knowledge after choosing the area of transport engineering for performance. In graduation, the disciplines of this area of knowledge are comprehensive and aim to present the greattopics that support transport engineering. Unfortunately, in Belo Horizonte, there was no possibility to perform a master's degree in this area. Thus, I researched some programs, collected some information on how to set up a pre-research project and enrolled in the programs of the University of São Paulo (USP)-São Carlos, the Federal University of Rio de Janeiro (UFRJ) and the Military Institute of Engineering (IME). The registration at UFRJ and the IME was in person and, at that moment, I decided on the IME. The choice was not based essentially due to the quality of the course, but due to the location of the EMI compared to the UFRJ Campus on the island of Fundão. The location was already manifesting itself as an instrument of decision in my life.
I was approved in the three programs anddecided to go to Rio de Janeiro, enrolling in the IME. The main factor for choosing Rio and not São Carlos was related to the ❤heart ️ ,  and the distance between Belo Horizonte and the respective cities was decisive.
I grew up believing that peoplecan conquer material goods and status through effort and individual merit. He believed that the possibility of generating value for companies was what differentiated a good engineer from a bad professional. Thus, avoiding looking at the public, Idirected my master's project for the transport of cargo, understanding, at that time, that I would be exempt from public decisions interfering in my academic project and in my professional activity .
2003 was a year full of change. Changes inego, home and goals. After fulfilling the basic credits in the IME, I decided to lock the course and return to Belo Horizonte. As I could not stay without work, I sought internship in the reference company in transport consulting in BH at that time: the grupo Tectran. I knocked on the door of Tectran's office, with my simple resume under my arm and asked if they had any openings for me. They found this approach strange, but I made myself available even to intern as a student at the company and m and madethe proposal to work as an intern receiving remuneration equivalent to that of the master's scholarship at the time. It was wonderful. Ramon Vitor César was my immediate boss and the activities I developed were already related to Geographic Systems, years before I thought about becoming a geographer. Ramón also had an important role in the ways to decision where to attend doctorate ❤️.
The staff was welcoming and, as the group was still small, I had the opportunity to pray with projectsin different areas and effectively learn to work. This was effectively my first professional experience as an engineer and I loved it! I loved not doing the same thing every day, I loved eventually studying to propose some methodological path for projects and to effectively complete stages throughout the professional life.
Also in 2003, in the midst of consulting activities, I got a placement, to act as a teacher at Faculdade Novos Horizonte. Interestingly, most of the students were more velhes than Me. I taught Logistics, Transport Management and Management of material and property resources.
I started at Vale in September 2003, after a long selection process for a Trainee program in Engenharia Ferroviária. The "most difficult stage of the selection process" was to resign from my position as an intern at Tectran. He had learned so much and nurtured affection for the people and the welcome he received. But life goes on and disconnecting me from that positionwas not closing doors; but seeking new experiences.
It was curious that, during the selection process, I went through two general managers in the final interview. The first to interview me identified my ineptitude to participate in routines and therefore to work on the operation of the railroads. What is not routine in railway operation, becomes a problem and if there is anything that makes me demostivada is to solve problems that could be avoided with due planning! The first manager to interview me forwards meor the second and the result was that I was the only "Railway Engineer" who was not crowded in the Operations Directorate. I was aswerded in an area of operational studies under the Planning Board. This decision of the managers was very assertive andthe line with my potential contribution to the company.
We took over at Vale, me and my coleges and amiges Engenheires Ferroviáries, on September 15, 2003. We entered the first edition of the trainee program "Railway Engineer", whose objective erto empower young talents to work in the railway market. For years there was no investment in Brazil in labor for the operation and management of railways. Thus, it was necessary for operators to invest in qualification, as it is still a reality inthe sector.
There were three months of classes and a lot of learning and travel, companionship and building new friendships. This training took place in immersion in the late Othon Palace Hotel of Belo Horizonte and, later, we traveled 15 days visitingthe di ferentes railway facilities of Vale on the railroads Estrada de Ferro Vitória a Minas, Estrada de Ferro Carajás and Ferrovia Centro Atlântica. Fortunately, during training, I stayed home (heart issues are strong!) and attended day-to-day classesat Othon.
I developed a course completion project entitled "Analysis of the Increase in Reliability of Grain Route Locomotives from the Implementation of the New Fca Traction Framework", under the guidance of my manager at the time, Leonardo Dallorto. It was a great challenge to explore the coordination between operating conditionsof railway components and the maintenance of these components. The time interval between the overload and the failure event of these components is a major methodological challenge.
Throughout the development of this project, I also collaborated with otherinternal improvement companies, working with railway dynamics simulators and evaluating operational interventions and investments. I breathed economic engineering and even some restaurants around the Federal Railway Network building, in bairro Floresta in Belo Horizonte, were nicknamed by the team as VPL (net present value), for presenting a great cost-benefit. I learned that the quality of my work is directly proportional to the time I have to do so. I had to learn to control the desire to do better, because the deadlines were not flexible and the delivery had to happen. I also learned that Vale was oriented towards capital remuneration, although permeated by decision-making processes exclusively based on disputes of market power and political capacity. I also found that principles, values, ethical commitment, the technical quality of engineering and even risk situations can be made more flexible if they promote shareholder capital remuneration.
Some monthslater, during one of the many management restructurings, there was my allocation to the rail planning area (long and medium term). This area was the interface between the commercial and operational functions of the railroad and we worked on the flowsto be carried out on the monthly and annual horizons. It was wonderful to understand a little more about the rail system as a service and become one of the people responsible for the sizing of wagons, locomotives and the arrangement of trains with all the restrictions that the Brazilian railway system presents. I was responsible for coordinating data obtained from different ERPs (Enterprise Resource Planning) that were different for each railroad. It also received data from the maintenanceareas of undercarriage and permanent track. Consolidating and coordinating the information, we generated an instrument called Book PPC (planning, programming and control) that was a set of spreadsheets with railway performance indicators. This document was forwarded to the entire Logistics Board in order to monitor goals and results, in the different measurable dimensions. Later, with the needs of research activities, this knowledge was useful in understanding the concepts of Business Analytics and Urban Analytics.
Still at Vale, I continued developing my dissertation, which was defended on August 2, 2004. Entitled "Neuro-Fuzzy Model for Modal Choice in Cargo Transport", it was developed by mim, under the guidance of Prof. Marcus Vinícius Quintella Cury. Teachers Maria Cristina Fogliatti de Sinay, Maria Augusta Soares Machado  and David José Ahouagi Vaz Magalhães participated in the newsstand.
The study aimed to implement a fundamentado method in fuzzy logic and neural networks to support the decision in the modal choice of cargo transport. Modal choice is a decision-making process that aims to meet the level of service demanded by customers, establishing a trade-off between logistics costs and the quality of service. The attributes involved in this decision-making process are not only objective, but also subject to subjective parameters, such as the reliability and safety of the available modal options. Exploring methods to support decision-making in modal choice, I felt uncomfortable disregarding the subjectivity of the decision-making process considering optimization methods. However, due to my little scientific maturity, I focus on the method and not on the problem para to draw the theme of the dissertation. Thus, I came across the Neuro-Fuzzy technology that enabled the convergence of quantitative and qualitative information to support the decision-making process, with the advantage of working the information without loss of subjectivity. Finally, the objective of this work ended up being to propose a method for modal choice, based on quantitative information and also on qualitative evaluations of specialists, using Neuro-Fuzzy technology. I closed this stage, without the joy I have today as a researcher. I even thought that there would never be a Renata-researcher.
The corporate environment and the work routine made me rethink my stay at Vale. In 2005 I decided to ask for a shutdown and recover my teaching activities. During my period at Vale, from September 2003 to May 2005, I could not coordinate my activities as a teacher and, therefore, requested suspension of my contract at Faculdade Novos Horizontes and stayed until 2005 linked tothe institution, but without teaching. Once again I am grateful for the confidence and opportunity to gain experience in teaching in higher education that this institution has given me.
In 2005, after vale's dismissal, I taught in private colleges in business courses and as a substitute teacher back to the Department of Transportation Engineering and Geotechnics of UFMG. The private faculties - FUNCESI - Community Foundation of Higher Education of Itabira and New Horizons College. They were unique,because achieving professional placements without experience is very difficult, hindering opportunities for the construction of experiences. It's the perverse cycle of any young man's early career. In these universities I taughtdisciplines related to the management of operations and the application of quantitative methods, such as production administration, quality and logistics. These disciplines were related to my basic training in civil engineering and my specialization in transportes engineering. The experience with corporate management at Vale helped me a lot, allowing me to contextualize the processes and problems that students faced in their professional activities on a daily life.
In 2005 I was also a substitute teacher at UFMG, and faced a professional challenge that had an emotional weight for me. Professor Baeta had to retire by age and I would take his place. He had been my teacher years before and, as always, was very helpful in making a smooth process of transitioning the disciplines for me. However, I felt bad about taking his place, and he would still like to practice teaching. I also disagreed with some classroom practices he adopted as a student and wanted to do differently. Once again it was going through a situation that required the imposition of the teacher at the head of the processes in place of a submission to the processes already installed. Positioning myself, to this day, is an emotional challenge for me.
In 2006, I joined CEFET-MG asan effective teacher . During the first years at CEFET-MG, there was no spark access within me indicating that one day I would become a researcher and that, for this, the doctoral process would be very important. However, institutionally, the title of Doctor was necessary.
The decision to study his doctorate in the Geography program at PUCMinas had a lot of heart involved and the central objective of reducing distances. Heart to decide not to seek programs outside Belo Horizonte; heart in lovewith Geography; heart beating out of the chest .
I decided to start slowly and know this field of knowledge to understand if there were possibilities for me to increase my training in transport. In 2010, with Sofia, my first daughter, at 3 months, I enrolled in the isolated discipline "Evolution of Geographical Thinking". There are people who when they go through our lives leave indelible marks. One of them was Professor Oswaldo Bueno Amorim Filho. Professor Oswaldo was able to weave the reasoning and coordinate the conceptual and temporal immensity that are the multiple geographies brilliantly. I could not not fall in love with the infinite possibilities and epistemological paths, sometimes ontological, of exploring physical and human phenomena. There was born the geographer who writes this memorial. That'sme smo: GEOGRAPH.
At the end of 2010 I participated in the doctoral selection process and formally entered this world of new horizons and perspectives. In the choice of advisor, I was referred to a teacher with very quantitative and functionalistworks, after all, I came from engineering. However, I chose to seek a mentor who would contribute to my training with new perspectives, leading me to understand the implications of geographic studies and their challenges. That's when I talked to Professor Alexandre Magno Alves Diniz. Besides being an excellent professional, whose area of expertise was aligned with my claims to work with the geography of transport, he is a human, kind and available person.
In the following years I studied the compulsory disciplines of the line of research in human geography, with emphasis on urban geography. It was a significant time between my entry into the program and the definition of the research problem. I had to do 48 credits to be able to meet theminimum requirement for a phD degree. It sounds like a lot, but despite two years of studying subjects, I'd like more 🙃.
In early 2013 my husband (once again the idea of reducing distances predominates in my personal, academic and professional decisions) got a six-month scholarship from the Université de Lyon to develop the experimental part of his research. There were scholarships available at PUCMinas for sandwich doctorate and I also got a program so that we could walk together on this journey. Atthe end of June 2013 we landed, I, Patrick, Sofia, John and my mother at Saint Exupéry airport. A lot of apprehension, news and detachments. Crossing the Atlantic with a six-month-old baby and a 3-year-old would be an adventure. Crossing the Atlantico with the little ones to live for six months was a huge adventure with a little madness. My mother went with us so that we could work and, at the same time, provide care to John. Without her, this adventure would not have been possible!   We comfortableher in a hotel on a provisional basis until we found a villa for our stay. Once again, the decision struck a balance between distances so that the location of our home would be as central as possible in relation to our laboratorios and the everyday life of children and my mother. Interestingly Patrick needed to move to the far northeast of the Lyon region and I to the far southeast. Fantastic experiences were seized while living in an unknown city, with local and cultural challenges, but without impedances for the displacement of people. We don't need an individual car to perform any of the day-to-day functions. The subway stations, access to articulated buses, reliability in the tables andschedules of the systems and even the fare were accessible. Vulnerable population, families with many children and other specific groups had public subsidies proportional to their needs. Who can more, pays more. Quem can less, pays less.
I was received at the Institut Rhônealpin des Systèmes Complexes (IXXI) by Professor Pablo Jensen. It was an incredible experience to see how research laboratories in France have autonomy in the structure of universities and why IXXI'sfísicos working with cities has remained a mystery to me for a while. Nothing in life happens by chance. Some time later, I understood how interesting is the application of complex systems, usually worked in basic sciences, withphysics and chemistry, to understand social problems. It was a pity that I did not have this maturity while present at IXXI, but this internship was important for me to understand the possibility of using the knowledge of this area as a researcher.
At the turn of the year 2013 to 2014 we arrived in Brazil. At home, I continued to develop my phD work and on August 20, 2015 I defended my thesis entitled "Spatial Analysis of Food Prices in Retail in Belo Horizonte and its relation with the average income of the population. As already mentioned, Professor Alexandre Magno Alves Diniz was the advisor of this work. Professors Sandro Laudares, Ana Márcia Moreira Alvim, Leise Kelli de Oliveira  and Karla Albuquerque de Vasconcelos Borges were part of the evaluation board.
A curious fact of this work is in the thanks of my thesis: "I thank the Pintadinha Chicken, the Cocoricó Gang, Discovery Kids and the other forms of children's entertainment that collaborated directly or indiretamente so that my puppies could have fun while I worked on the preparation of this document." I think thanks dispense with comments 😂.
Today, revisiting my doctoral work, I am happy to see thatin that context I already had spatial inequalities and social inequities considering access to low-order products, especially food. I discussed the spatial heterogeneity related to socioeconomic and demographic attributes of the population that resides in the vizinhanças where the commercial establishments are located. The central objective of this study was to identify possible relationships between the population's income and the prices of first-rate foods practiced at different retail scales: local markets, supermarkets and hypermarkets.
For this, a secondary data collection was performed that subsidized the determination of a sample of retail points that were visited. In these points, the prices of a list of nine food productsof first need were raised, generating a database that was spatially processed, weighted according to a composition of areas and following the concept of decay of distance in relation to the areas of influence determined for each commercial establishment. The variable average monthly household income was also determined for the same spatial unit considered as a reference for prices, generated by Thiessen polygons for commercial establishments of lower porte. Considering the spatialized income and price variables, ordinary regression analyses were performed, taking income as an explanatory variable and price as a response variable. A strong spatial autocorrelation of the residues was identified, which indicated the need to explore the relationships of the variables through local/spatial methods. A geographically weighted regression analysis was then performed. The results indicated a better fit of the local models for the various products pesquisados and for the respective basket of products. In general, a predominance of positive variation between income and price was identified, which indicates that, for most products and in most areas of the municipality, the higher the income of the local population, the higher the prices charged by the retail trade of first-need foods in their neighborhood.
It was a result that refuted my initial hypothesis that low-income people pay higher prices for essential products and foods, but this time I was very happy with the result of my work.
________________________________________
The birth of Renata-researcher
On May 19, 2017, I formalized my accreditation in the Graduate Program in Geotechnics and Transport (PPGGT) at UFMG. The program needed the participation of more teachers and, if I wanted to progress in my career as a researcher, I would need this space. I was welcomed by the Professor. Leise Kelli de Oliveira, who introduced me institutionally to the world of academic research. We were partners for a while, but gradually I was building my identity as a researcher and our paths distanced themselves.
The first discipline I taught at PPGGT was Transport Geography. It was a dream. A wonderful energy of the class when understanding engineering constraints that are directly related to the location of activities, the morphological structure of cities and regions, spatial interaction as a fact that generates the demand for transport and the concepts of accessibility.
I also taught a discipline of Transport Planning and tried to make an approach from critical and practical perspectives,developing and developing integrative projects throughout the discipline, based on incremental problems.
The performance at UFMG is very rewarding. Excellent students and researchers in training and autonomy for the development of research projects andacademic work. However, UFMG, despite being my academic cradle, is not my home. It is very difficult to keep effectively collaborative to the program with institutional  distance. I tried a few times to coordinate the work of scientific initiation scholarship students  from CEFET-MG with students of the PPPGT master's degree, but the  physical distance was also a limiting one for this interaction. Perhaps, from our experiences in the remote context, we will be able to enable more assertively the structuring of a support network and the coordination of the development of research projects. Once again, distance determines my choices. More pragmatically, acting in the PPGGT is an exercise of detachment, because although UFMG and CEFET-MG are two federal higher education institutions, there is no assignment of teachers to assign academic burdens in a collaborative manner. Thus, for CEFET-MG, this activity in the PPGGT becomes an additional elective burden for the professor, not being counted in thecalculations of the academic tivity of the professor formally. I believe that we still have a long way to go until we can effectively understand that without collaboration, we cannot produce knowledge.
On 31/07/2021 closes my accreditation in PPGGT. It is theclosing of a long cycle of comings and goings at UFMG. It remains my academic cradle, but I need to walk and CEFET-MG is an institution that needs my dedicated work and that enables this work with a series of incentives.
I thank my students nesse period. Patience, collaboration, discussion, and learning. I thank each student who has developed his work under my guidance:
•	Clarissa Pontes Melo - Analysis of the macroaccessibility of elderly pedestrians under thequality of urban space. 2021.
•	André Augusto Cunha Libânio - Evaluation of accessibility in Brazilian cities. 2020.
•	Paulo Henrique Góes Pinto - Identification and qualification of urban centralities through morphological-functional structure: a case study for RMBH. 2020.
•	José Moreira Gonçalves - Attraction of Cargo Travel in The Automobile Industry of Agricultural and Road Machinery. 2019.
•	Gabriela Pereira Lopes - An Analysis of the Location of Logistics Facilities versus Travel Generation and the Impacts on urban mobility in Belo Horizonte. 2018.
In 2020 I graduated from the Graduate Program in Administration of CEFET-MG (PPGA). A priori requested accreditation as a collaborator, but, promptly, I was accredited as a teacher of the permanent core of the program. The program's area of concentration is Processes and decision-making systems in organizational arrangements. Much of what I do as research today and I have done over time is related to decision-making processes.
I amor ientando the student Sofia Eleutério who develops a work on the effectiveness of exclusive bus lanes as public policy. It's been very gratifying to discuss the same problems from different perspectives.
I am in the ppga collegiate to workwith the administrative and academic structure of the program and to learn how are the rules, demands and challenges of graduate programs in Brazil. It's a lot of work, but also a lot of learning.
I have invested a lot in the process of internationalization of my activities as a researcher. Since 2015 I have participated in conferences abroad and research networks.
Although I disagree with the dissociation between research and extension, I havetried to specify projects focused on technological transfer and the dissemination of knowledge to society. Among them, I quote three that were very nice experiences: (i) collaboration with Horta da Cidade in planning the delivery of vegetables; (ii)  paradise of Tocantins mobility plan; and (iii) organization of the 1st Brazilian Urban Logistics Forum.
The first project was special because it refers to the technical support to Horta da Cidade, whose business is oriented to the production of organic vegetables in idle lands in urban areas. In this collaboration, I had the opportunity even to participate in business acceleration events with SEBRAE-MG, as in the following photo.
The second extension action was the participation of the elaboration of the Plan of Mobilidade Sustainable Urban of Paraíso do Tocantins, coming from a partnership signed between UFT and the Secretariat of Infrastructure and Public Services of the Municipality of Paraíso do Tocantins. The objective of this plan was to define strategic actions to achieve the desired urban mobility scenario for the city, in accordance with the National Urban Mobility Policy. I was invited to collaborate with this project in the development of urban studies oriented to accessibility to includethis paradigm in the diagnosis and proposals for interventions. It was my first opportunity to directly apply accessibility measures in planning and the work team was wonderful!
The third action is more in line with the proposal to diffusescientific knowledge and is one of the examples of initiatives with which I have been involved. This action was the organization of the 1st Brazilian Urban Logistics Forum, the result of a partnership between UFMG, CEFET-MG and UFT. As a result of the event, in addition to all the very rich discussion, we had a book published
Other actions of dissemination of knowledge that I have done are the participation of technical committees and events promoted by the municipal and metropolitan public management as theLogistics Forums ur bana promoted by the city of Belo Horizonte and, more recently, the technical committee of Mobility of RMBH. Actions like these are one of the goals that are on the agenda for the coming years and my participation as co-tutorin the Tu torial Education Program of Adminstração has a lot to do with this desire.
Still as a researcher, I have collaborated with different journals, national and international, as an ad hoc reviewer. Among them, the magazine Transportes, IEEE Access, Sustainable Cities and Society, Research in Transportation Economics, Transportation Research Record and Urban Rail Transit. Today I am part of the editorial board of the magazines Caderno de geografia and revista Brasileira de Transportes.
I have participated in evaluation papers of completion of Doctorate, Master, Specialization and graduation. The geographical scope of this participation is quite broad, but still restricted to Brazil. Among them are the Graduate Program in Mathematical and Computational Modeling of CEFET-MG,the civil engineering program of UFT, the graduate program in Transport Engineering of UFC, the production engineering course of UFSCar - Sorocaba and the Graduate Program in Production Engineering of Campus Sorocaba, also of UFSCar.
I believein internationalization so that it is possible to establish partnerships not only of research, but also of teaching. I have participated in the institutional initiatives of teacher training in English as a medium of instruction, concluding a 40-hour training in July 2020, of international conferences, such as:
•	4th VREF Conference. Relationships between urban characteristics, real estate market and spatial patterns of warehouses in different geographic contexts. 2021. (Congress).
•	11th International Conference on City Logistics. EXPLORATORY ANALYSIS OF THE ACCESSIBILITY TO FOOD RETAILERS IN BELO HORIZONTE. 2019. (Congress). 
•	15th biannual NECTAR Conference. ACCESSIBILITY TO FOOD SYSTEMS IN BELO HORIZONTE, BRAZIL. 2019. (Congress) . 
•	6th WORKSHOP NIUMAR. Projects under development and research agenda. 2019. (Seminar). 
•	1st Brazilian EMI. 2018. (Seminar).
•	NIUMAR's 2nd workshop. Research development. 2018. (Seminar).
•	3rd NIUMAR workshop. Partnership prospects. 2018. (Seminar).
•	4th NIUMAR workshop. Referrals. 2018. (Seminar). 
•	Nectar Cluster 2 Workshop. A sustainable business model for urban farming based on city logistics concepts for local production and consumption of vegetables. 2018. (Seminar).
•	Efficiency in Urban Logistics: Current challenges, innovative & green solutions. 2017. (Seminar). 
•	Researchers Links Workshop: How the Railways contribute to improving quality of life?. Researchers Links Workshop. 2017. (Seminar) . 
•	International Week of Metrorail Engineering, Transport and Logistics. Spatial analysis applied to solutions for the last kilometer. 2017. (Seminar). 
•	Tenth International Conference on City Logistics. Urban Distribution of Craft-Brewed Beer in Belo Horizonte Metropolitan Area. 2017. (Congress).
In October 2020 I started a research activity in partnership with logistics city chair, université Gustave Eiffel, through a remote postdoctoral opportunity. The project was titled Relationships among urban characteristics, real estate market and spatial patterns of warehouses in different geographic contexts. The duration of this activity was 5 months, being in the process of completion. Formally, this was a postdoctoral research underthe guidance of Professor Dr. Laetitia Dablanc. My role as a postdoctoral researcher was to investigate the changes in the location of warehouses in different metropolitan areas and their relationship with the urban structure and the practices of the imobiliary market.
To paraphrase Plato again... 
"To produce knowledge, you need Eros" Renata
My ways as a researcher have changed a lot. From the idea that She would never be a researcher, until she effectively found pleasure in scientific research. in 2018, despite having some consolidated partnerships and starting scientificcommunication through publications in journals and events, I was not happy. I wasn't happy I didn't see my contribution to changing the world . Urban Logistics is still a theme on which I have  developed works and intend to understandthe movement of goods in cities as a result of interaction and human decisions. I want to discuss not only how to mitigate the impact of urban freight transport on the city, but also how equitable access to essential produtos, such as food, can promote food security, quality of life and ensure the sustainability of the urban way of life. I want to build projects that gap easevidence the social abyss and allow the reflection of academia, public managementand citizens.
Today I can see what makes me happy! But I only got this research perspective like Eros in my life after I found some inspirations. It was an active search , but it depended on the opening of the other party to listen to me, to make room for my participation and to establish exchanges. I'm going to make a report far short of the importance of these people in my life, but come on!
In 2018 I made contact with the researcher Camila Soares Henrique Fontanele Garcia, after seeing hiswork through publications. What she did was REALLY cool! I sent a message through the chat, unpretentiously! She answered and we set up a conversation. I don't know if it's related to  the origins or the person, but I became even more in love with what thegirl did. It opened the opportunity for me to participate in the meetings of the research network I was building together with other researchers from different locations and, fortunately, CEFET-MG saw the importance, fostering my participationin some events of NIUMAR - Network on Intelligente Urban Mobility and Accessibility Research  . It was through this participation that I discovered: (i) what motivates me; (ii) who I want to be (wonderful inspirations as researchers and human beings);  (iii) how I like to work.
Briefly naming these people, at the risk of leaving someone out and already apologizing, I 😬 thank the following researchers:
•	Carlos Felipe Grangeiro Loureiro
•	André Soares Lopes
•	Camila Flag Cavalcante
•	Francelino Franco Milk of Matos Sousa
•	Francisco Gildemir Ferreira da Silva
•	Bruno Vieira Bertoncini
•	And all the other researchers from NIUMAR and other groups who strive to contribute to a better world.
I also thank some partners that academic life has brought me, but who have been confirmed as excellent friends and companiones in this search for a better world:
•	Lílian dos Santos Fontes Pereira Bracarense
•	Jose Geraldo Vidal Vieira
•	Lucélia Viviane Vaz Raad
•	Ludmila de Vasconcelos Machado Guimarães
•	Joana Ancilthe Strong Person Avelino
Closing this episode of my career, some events that materialized success in specific aspects and moments. I have received some awards throughout my career:
•	One of the 12 best articles presented at PLURIS 2018 (Congresso Luso-Brasileiro for Urban, Regional, Integrated and Sustainable Planning), contemplated with publication in the Portuguese Journal of Regional Studies.
•	Best monograph of the Course of Administration of funcesi's 2005 undergraduate class.
As a teacher, I received eight honors from students graduating from the technical courses in Transport and Traffic and Civil Production Engineering at CEFET-MG, the Administration course of the Community Higher Education Foundation of Itabira - FUNCESI and the Course of Administration of Faculdade Novos Horizontes.
Today I am a productivity fellow 2 cnpq, with great pride! It is a recognition of this journey of hard work to date and i hope it will be long!
Some relevant publications with the works I have already developed are: [@DaSilva2020a; @DeOliveira2016a; @DeOliveira2017aa; @deoliveira2019a; @DeOliveira2019aa; @DaSilva2020c; @DeOliveira2016c; @DeOliveira2017ac; @deoliveira2019b; @DeOliveira2019ab; @DeOliveira2020b; @Furquim2018b; @guedesfurquim2020a; @guerin2021; @Oliveira2017b; @Oliveira2017aa; @Oliveira2018aa; @Oliveira2018ba; @oliveira2020a; @oliveira2021]
Me and CEFET
At the end of 2005 I received an email from Professor Heloísa Maria Barbosa of the Department ofTransport engineering and Geotechnics of UFMG, stating that a contest was to be held at CEFET-MG, for the transport area.  There were two vacancies and I registered unpretentiously, because the bibliography for the contest was very oriented to trafficgenharia. I decided not to prepare for the contest, because the deadline was short and I could not organize myself to study. I bet on the idea that we are prepared throughout academic training. And it worked! I took the theoretical test, i was in secondplace after writing more than 20 laudas. I delivered the documentation and lucky my theme for the didactic test: Projects Viaries. Heloise was one of the members of the board and had been my teacher of this content specifically. How could I teacha class for my teacher on a subject she had taught me about that I had not specialized on?
I decided to concentrate my efforts on the pedagogical organization of the class, elaborating a structured lesson plan and highlighting much more the proposal than the content. At that time I already had a few years of experience as a teacher, despite no formal teacher qualification. I think the class was good, because I was approved for one of the vacancies and, on February 10, 2006, I took possession.
Ijoined CEFET-MG in the coordination of technical course in Transport and Traffic. We weren't a department. We were two course coordinations that included the transport and traffic technician and the road technician each. Everything was new. From the idea ofteaching for teenagers (I felt and still feel like a teenager), to the structure of a public educational institution. I promptly received the position of coordination of laboratories of the courses, which provided mewith a quick learning about how institutional management, purchasing processes and trading sessions worked, the management of the demand for laboratory insums. A few years ago I did not see a casagrande device (I confess that I had to research the name to write it here!) and I had to relearn some of that universe of geotechnics and know implementations in asphalt, infrastructure and road superstructure. Through this performance as a laboratory coordinator I met many people in the institution.
I knew the organizational structure. At that time there was still little formalization of institutional processes and, therefore, personal relationships were essential for the processes to be executed. There was no digitization of the means of formalization of institutional demands and positions andlittle to the oction of human resources dedicated to administrative functions. We coordinators were responsible for writing minutes, memos, physically distributing documents around campus. I confess that this personality and the slow conduct of the ad ministrativeprocesses bothered me a lot, and everything I could "digitize" within the coordination, I did.
Soon I became coordinator of the road course and then Transport and Traffic. I performed some coordination function until 2009, when I enjoyedmaternity leave. Among the administrative activities I have already performed, the coordination of courses is the most interesting. It includes active participation in collegiate bodies responsible for pedagogical and curricular discussions. I learned a lot abouthow national curriculum references for professional and technological education  and how they are the basis for the construction of the structure of technical courses. I discussed institutionally and built arguments for the MEC focusing on the need to adapt the technical course in Transport and Traffic to the National Catalog of Technical Courses (and vice versa). I held numerous meetings with students and family members in the search for solutions to family and personal difficulties in relation to the institution.
As a professor,between 2006 and 2016 , I taught essentially in the technical courses of the coordination that became Department of Transport Engineering from the implementation of the Transport Engineering course. I have consistently ministered the disciplinas "Cargo Transport Management", "Cargo Transport Operation", "Transport Policies and Planning" and "Administration" for technical courses.
In 2008 we elaborated and implemented the restructuring of integrated technical courses,and the disciplines became annual, with changes in the curriculum structure of the courses. The disciplines of technical courses in the external and subsequent concomitance modality (when the student does not attend high school in an integrated manner to vocational education) were offered in the night shift and the curricular structure did not suffer important changes. However, for the integrated daycourses (vocational high school), the disciplines I started teaching were called "Logistics", "Transporte cargo Eventually taught some disciplines for Civil Production Engineering, such as "Physical Distribution of Products and Layout" and "Logistics".
In November 2009 I left the functions of coordinating courses/laboratories to be a mother. Immersed in maternity leave, I was absent from all professional and academic activities. That year, before the leave, I participated in the restructuring committee of the political-pedagogical project of the Transport Engineering course, which was institutionally approved in 2012 (@ref(fig:eng)). It was a very special project, especially because it is another offer of free night engineering courses, consolidating itself as a synthesis of this area of knowledge in the training of professionals and in a process of inclusion due to access to students who need to work.
Returning from the license in 2010, I was already studying isolated disciplines inpucminas' geography program and reconciled academic and administrative activities until, in 2011, I enjoyed a license for training. In addition to all public investment in my academic background from higher education, CEFET_MG was very important in thecon tinuity of my training. The institution effectively invests in the qualification of human capital. I obtained a license of 3.5 years and financial promotion for payment of doctoral fees.
As the subjects of the heart permeate my entire professional andacademic life , I became pregnant with John in 2012, still studying doctoral disciplines. John was born in December of that year and, six months later, we embarked for a doctoral-sandwich period in France. I was not immersed in motherhood during the license afterthe birth of John, because I lived new academic challenges .
In 2015, despite still being in the process of completing my doctoral thesis, I returned to activities at CEFET-MG. I assumed the under-coordination of Transport Engineering already with a setup forme to become coordinator as soon as the doctorate was completed; and so it was done.
On August 20, 2015 I defended my doctorate and took over the coordination of Transport Engineering. 2015 and 2016 were years of hard work, as the course was in implementation. As coordinator, in addition to the attributions of the routine standardization of the collegiate, I was responsible:
•	by reviewing the pre- and correquisitostines of the curricular matrix of the course, in alignment with the equalization of disciplines of the institution;
•	byregulating the collegiate of the undergraduate course in Transport Engineering;
•	by the establishment of criteria for the classification of candidates for remaining vacancies to obtain a new title;
•	by regulating the structuring teaching center of the undergraduatecourse in Transport Engineering;
•	for the activities of monitoring curricular internships of the undergraduate course in Transport Engineering;
•	coordination of the beginning of discussions on a minimum curriculum and professional qualifications between transport engineering and mobility courses in the country. CEFET-MG hosted the first meeting of the representatives of the
I also participated in the construction of the regulation for the completion of the course for the undergraduate course in Engineering of Transportes and the entire organization process to receive the MEC in his visit of recognition of the course. After the visit at the end of 2019, the course received top marks in its recognition!
Considering institutional administrative functions, I already participatein and participate in different temporary and permanent committees, such as:
•	Cep/CEFET-MG Research Ethics Committee;
•	Thematic Chambers of the Initiation Committee;
•	Participation in Examining Benches of the Public Competition of Tests and Titles to provide loads of the career of Teaching Of Basic, Technical and Technological Education;
•	Participation in simplified selection process examining benches for substitute/temporary teachers;
•	Other temporary committees;
•	Collegiate Of the Graduate Program in Administration ;
•	Collegiate of the undergraduate course in Business Administration .
From 2017 to 2019, in addition to those taught in the technical courses, I taught the following disciplinas for the transport engineering course:
•	Introduction to transport engineering;
•	Special topics: Transportation Geography;
•	Urban Logistics;
•	Supervised internship guidance;
•	Completion of course I;
•	Completion of course II;
•	Cargo transport management;
•	Rail planning.
There are many courses, but all have, in some dimension, part of my essence as a researcher. Ministering the discipline "Introduction to Transport Engineering" was very special. First, itcan be the discipline responsible for presenting this area of knowledge in an integrated way to students. Second, because the doctorate in Geography made me understand the need for the social, economic, political, environmental, cultural, historical and locational context so that we can understand any natural or social processes. So, for this discipline, I needed to:
•	to discuss the paths of humanity in technological constructions [@harari2015a; @bazzo2013];
•	explore the history of engineering and the contexts for this area of knowledge to begin to be built [@svinicki2013; @ensinod2006; @êlmorfilho2019; @bazzo2013];
•	discuss with students geographical foundations such as spatial interaction at different scales and shapes,boosting technological advents in the historical and geographical construction of transport systems [@modernt1992; @blunden1971; @taaffe1973; @bavoux2005; @thegeog2004; @shallat2010];
•	discuss the technological foundations of transport technologies.
In 2020,I had a renewing journey at CEFET-MG. I changed departments and went to the Department of Applied Social Sciences .
In my first semester at DCSA, I had to teach the quality management discipline. I hadn't taught this content for 15 years and a lot had changed in my way of seeing the organizational, social world and the role of teaching in this context. We were also surprised by the emergency remote teaching, due to the social distancing recommended as a non-pharmaceutical measure to support the diffusion of SARS-CoV-2. I confess that Quality Management would not be by far my first option. I went through the document the times I ministered on this discipline and found that I couldn't take advantage of anything I had previously produced.
I think we can deliver any content from different perspectives. In 2005, when I taught Quality Management, I had a positivist approach to the discipline, presenting tools and functionalities to students. It is usually the proposalof the textbooks. However, in 2020, my effort in ministering this discipline was to make a critical analysis of Quality Management considering:
•	the chronology of the concepts and how they were incrementally being changed;
•	private organizational function and contemporary challenges related to social and environmental responsibility;
•	the rethinking of the role of process standardization in a context of 4th industrial revolution in which machines are responsible for decision-makingprocesses and the most demanding competencies of professionals are creativity, collaboration capacity, empathy, flexibility, communication capacity, critical thinking, leadership, the initiative to foresee situations that may be inadequate to the production process.
It was very interesting to explore more conceptual discussions about the production processes than just to instrumentalize the students and explore this proposal in full remote education because of the pandemic.
Also in the first semester of 2020, I was presented with an optional discipline entitled GIS and spatial analysis for social sciences. It was a huge challenge to build instruments so that students could appropriate the conceptual elements and tools that allow spatializing information to understand the processes related to the social sciences. It is always a pleasure to offer a course that allows you to present and discuss the most interesting fundamentals that you have learned.
In the second semester of 2020, aligned with the discussion I present in the episode @ref (for-where-i go) of this memorial, I offered two similar disciplines, one for graduation (Data analysis for organizational management) and another for the Master's degree in Administration (DataAnalysis applied to the decision-making process).
It was very challenging for a few reasons:
•	much of the content I would still need to learn;
•	we were and we followed in remote teaching;
•	courses depend on conceptual aspects and the development of practical skills;
•	I understand data science as an instrument of resistance, counterpoint to the post-truth and needed, in addition to discussing concepts and facilitating practical learning, fazer discussions on social responsibility, politics and ethics in data manipulation.
I had to review the course planning a few times. If there is a key term for remote education and, more generally, for the pandemic, this term is adaptação. In discussion with the students, everything went well and, in the end, the resistance to the use of R as a platform for data analysis and production of communication instruments were broken and the understanding of potential ethical risks in data manipulation were understood. At least that's what I realized about the students' feedback and our interactions.
I have been telling the students that my role as a tutor is to unseethe possibilities. But it's the students who are going to exploit them.
In disciplina Logística, also taught in the second half of 2020 for the Administration course, I revisited a theme that I have long been teaching but i wanted to present from a more critical perspective. I leave to the appendix of manifestos of this memorial the critical argument ation in relation to logistics processes as increasingly necessary and less socially and environmentally responsible.
This week we started  the first semester of 2021. I have excellent expectations of resuming the urban processas a context of discussions with the Master's degree in Administration. I will teach the course Quantitative methods to support decision in urban management. I intend to study a lot and explore the planning of cities not only by the knowledgeprovided by Architecture and Urbanism. I intend to study and learn together with the students concepts related to "Urban Analytics" and its consequences in the computational representation of space (geocomputing) and possible analyses as an instrument of theirown decision.
My battle gear for this semester that begins are ready!
Throughout my 15 years of CEFET-MG, I have had many students under my guidance. I guided projects of junior scientific initiation, scientific initiation, course completion papers and master's dissertations. Some of the Scientific Initiation students are listed below.
Student	Project	Year
Alice Fernandes Lages Ferreira	Reverse Supply Chain Determination for Craft Beers produced in the Metropolitan Region of Belo Horizonte	2016
Almir Silva Ribeiro Junior	Analysis of the preferences of potential consumers in relation to accessibility to collection and delivery points of orders in Belo Horizonte	2019
Caio Vitor Malacco of Lima	Railway Macro-Analysis: proposals for Brazil	2017
Caio Wanderson Nunes Alves	Urban agriculture as an instrument for the construction of Livable Places	2018
Camila Silva Coelho	Avaliação of the Urban Distribution of Goods in Medium Cities	2016
Camila Silva Coelho	Analysis of urban accessibility in Belo Horizonte	2018
Camilo Santana Melgaço	Analysis of urban accessibility in Belo Horizonte	2018
Guilherme Fonseca Graciano	Urban production and distribution of vegetables in the metropolitan region of Belo Horizonte: a social approach	2017
Ian de Paula Caliari	Accessibility as an instrument for promoting quality of life in urban centers	2018
Ian de Paula Caliari	Spatial Analysis Applied to Urban Logistics	2016
Ian de Paula Caliari	Spatial Analysis Applied to Urban Logistics	2016
Igor Santos Paranhos	Spatial Analysis Applied to Urban Logistics	2016
Karen Carolina Martins Julião	Spatial modeling of the distribution of goods in Brazilian cities	2017
Marcela Cristina Costa Branco	Analysis of the preferences of potential consumers in relation to accessibility to collection and delivery points of orders in Belo Horizonte	2019
Mariana Souza Lima	Evaluation of the curricular guidelines of engineering at CEFET-MG: a study based on skillsand skills	2018
Pedro Henrique de Andrade Fabossi	Analysis of the preferences of potential consumers in relation to accessibility to collection and delivery points of orders in Belo Horizonte	2019
Suellem Cristina Ferreira	Urban production anddisposal of hourly hours in the metropolitan region of Belo Horizonte: a social approach	2017
Suellem Cristina Ferreira	Evaluation of Urban Distribution of Goods in Medium Cities	2016
Thiago Henrique de Oliveira Faustino	Investigation of the operational viability of electric bicycles in Belo Horizonte and the impacts on access	2019
I received students/trainees from France, Germany, Poland, Serbia and Jordan through the agreement between theSecretariat of International Relations of CEFET-MG and ABIPE (Brazilian Association of Professional and Student Exchange).
I hope my history with CEFET-MG does not end here.
When I returned from this exchange period, ... 
Where am I going to go?
Motherhood is full of demests, challenges and uncertainties. Our lives change so much that we can't remember what we were before and what we did with the time we had left. It would be intuitive to think that mothers are less productive or that the world of work may be less important becauseof the birth of children. I disagree with this thought that sometimes dominates our society and ends up undersome public and corporate policies.
When my first daughter was born, a new Renata was born. A Renata more attentive to the world and more respinsável with its surroundings. Renata was born who wanted to change the world! I know this memorial is professional, but I can't dissociate the social roles I play with my emotion and my feelings. Renata-mother, at the age of 30, believed she could mugive the world. He became more rebellious to institutions, more critical and productive. It was a very significant moment in my life in the permanent transformation we have lived through.
At 40, I'm still thinking about changing the world . But I don't see myself as someone who can change the current way of life. I see myself as someone who can manifest himself insubordinately to the principles of this way of life and provoke reflection.
________________________________________
I teacher
"To teach, you need Eros" Plato
Life is full of changes and choices. Every choice we make impacts us, impacts those in our surroundings and those who are very distant  from us. Reaching my fourth decade of life has been a different experience from those previously lived. At 30, we think much more about thematerial and immediate r esultado of the work we have developed than in the simple potential increment that each reflection can bring. At 30, we think we can change the world. At 40, we are sure that we will not change the world, but that we can work to move questioning, reflection and discussion; to eliminate the dichotomy of arguments; and so that, gradually, we can see changes in the small everyday choices that we make and that people close to them make . It is much more an act of resistance than an effective and productive action, with tangible results.
I have also reflected on my role in the world as a researcher and as a teacher. The idea of science based on the principle of separation between the subject and the object is another issue that has motivated me to reflect on my career as a researcher. Contemporary discussions about science have presented the need to unwork hegemonic positivism, objectivity and functionalism in the production of knowledge. The observer does not isolatehimself, as a subject, from the object investigated and, not always, it is possible to quantify natural and human phenomena .
Today I see very great convergences between my criticisms as a researcher to the process of knowledge production and as a teacher, in relation to the process of disseminating this knowledge. I have thought about how much power relations influence thephenomes I investigate, as well as students in their learning.
"What makes power stand and is accepted is simply that it not only weighs as a force that says no, but that in fact it permeates, produces things, induces pleasure, formthat is, produces discourse. It should be considered as a productive network that crosses the entire social body much more than a negative instance that has the function of repressing." @foucault1979, p.8
When I think of the layout of the classrooms of a tradicional school, I think of lined portfolios, inhibiting the interaction of students (because through interaction there can be a stimulus to reflection) and promoting the distance between the teacher and the student . The space is designed to strengthen this distancing. It is designed so that students only focus on absorbing the information presented. Assessment tools are designed for students to reproduce what they have absorbed. And the resultis measured objectively, quantitatively and functionalistically, feeding the valuation of the tangibility of the end and devaluing the complexity of the path. And so humanity follows... 
For some time, I have rethought my performance as a teacher, tentando position me as one that leads the student to reflection and not as the one who presents the information. I feel like a curator of instruments that promote critical thinking in a coordinated way and that allow the effective construction of the knowledge o. My greatest challenge as a teacher is to lead the student to the place of protagonist in the teaching-learning process. It sounds simple, but it's not.
Since I changed departments, I have proposed offering  disciplines that address topics over which I haveno mastery. These are themes related to the concepts, methods and discussions that I do as a researcher, but that have not yet been part of my moments of study. The cool thing about this offer is not just that I actually have to study. It is breaking the distance that knowledge , as an instrument of power, can promote between teacher and student. Offering courses on topics not yet explored by me, I learn with the students. Even in a remote context, it has been very gratifying to realize the advances I have made, especially in relation to motivation and the promotion of autonomy in learning, through this rupture.
Subordination eliminates freedom and autonomy. But in the name of freedom centered on individual choices, the ability of collectivedivision, to look at the other, to reduce inequalities is eliminated. On the other hand, collective decisions limit the individual's freedom in their choices.
In order also to stimulate autonomy in learning, I have sought gamification. The use of games possibilita put the individual in a position of the one who makes a decision and who is influenced by the decision itself. In one of the activities presented in the following figures, we play Urbalog. It is a game developed by the University of Lyon and distributedfor translation and implementation both in the educational context and in situations of collective construction of social participation.
One of the most interesting aspects is that individual decisions about investments in the city may not result in individualbenefits. And collective decisions, after negotiation and concent, are usually more beneficial to everyone.
Another very interesting approach I took in the classroom was to allow students to exchange. Exchange of information, knowledge, perceptions. The following photos were part of an activity of characterization of the modes of transport for cargo handling. It would be some exhibition classes, with little capacity for interaction until the students were able to participateactively.
Instead of the exhibition classes, I bought cartolins, canetinhas and glue, printed terms and definitions that I would consider in the characterization of modes of transport, cut out and mixed. The students needed touse the terms and definitions to make up a coherent reasoning that would be considered in a later dispute between the groups about what they learned. I have sized two meetings for the activity and we spent a month building the elements that would result in the addition of technical and technological characteristics, operational constraints, planning challenges, advantages and disadvantages in each mode.
In the end, the dispute would not be necessary to promote learning, but it was a funsup er closure. The students researched, discussed what they understood, questioned and I followed as the one that coordinates the learning process and instigated reflection, redirecting the reasoning when not coherent.
These are some experiences that pretendo amplify and take to other courses and contexts. Unfortunately remote teaching brings other challenges, but I hope we can get back into interpersonal relationships as only closeness can promote.
I have studied much less than I would like,but bus co every day new references to change, always, the Teacher Renata [@filatro_metodologias_2018; @bacich_metodologias_2018; @bazzo2013a; @brown_design_2017; @brown2017; @bueno_no_2018; @miranda2019; @svinicki2013; @bacich_ensino_2018; @burke2015; @horn2015].
I also mention a recent fact: it took a pandemic for us, as a family, to decided to change the school children; from traditional confessional teaching to a wonderful project! 
I close this section with a review of Plato's sentence .
To LEARN, you need Eros.  Renata
________________________________________
I researcher
"Objective knowledge requires the subject, subjective interaction and also projections of the subject's mental structures. (..) Knowledge is always translation and reconstruction of the external mundo and allows a critical point of view on knowledge itself. (...) knowledge, without the knowledge of knowledge, without the integration of the one who knows, the one who produces knowledge is a mutilated knowledge." @morin2000, p.53
Idon't want to close the discussion of my future ways with certainty! I just want to put reflections and desires that I intend to consider as a background or conditioning of my research and teaching activities in the coming years. The only certainty I'm going toget what makes me happy and completes me. That is, I am part of the production of knowledge!
The city
Cities are the main habitat for humans worldwide, and urbanization is an evolving process. The logic of urbalife is supported by the need for cohesion in human interactions, where essential activities such as housing, commerce, work and education are accessible to all; however, the territorial distribution of urban functions and their connectivity is not equitable. Land use and transport systems are valuable resources for connecting people and activities, playing an essential role in the development of sustainable cities.
Research and policy formulation in relation to the connectivityof urban functions have been supported by traditional transportation planning based on demand and supply modeling. This approach has focused on increasing speed, efficiency, comfort and safety in the mobility of people and goods. In thisparadigm, but this paradigm defends transportation as an element of the urban environment, it does not necessarily consider urban structural components or the human dimension when designing our cities. In addition, contemporary global challenges – climate change, disruptive technological transformation, global migration and, finally, sars-cov-2 pandemies – make it difficult to implement demand forecasting models; these changes affect economic structure, urban dynamics, consumption patterns, direction and intensity of movements, compromising forecasting in the short term. Recent epistemological discussions have emerged on the need to structure a more comprehensive approach to investigating urban systems. As a result, we live the possibility of a paradigm shift in accessibility-oriented planning, which focuses on the integration of subsystems such as activity localization, land use and transportation structure in urban planning.
"We must complexthe mode of knowledge (...)" @morin2000 p.59.
I have reflected on how to change the city and how individual and collective decisions happen. We have numerous perspectives to explore the world, the natural, social phenomena and their interactions and respect for the complexity of phenomenhas appeared on a recurring basis in my explorations.
I believe we are moving towards an epistemological revolution also of geography. Maybe we won't have a complex geography school in the near future. Dissociating the natural and humanphenomena from the space where they occur is to lose the diverse and connected constitutive essence. Nothing more geographical than the idea that complex thinking "is not a manipulated concept, it is to integrate in itself a vision that seeks multidimensionality, contextualization. @morin2000 p.59
Theoretical knowledge and modeling are essential for the investigation of cities. However, innovative, human-scale solutions should consider best practices and the implementation of living laboratories. These approaches have become alternatives to the generalization of theories in order to address the contextualized specificities of decision-making and politics. The 2019 Nobel Prize in Economics, awarded to Abhijit Banerjee, Michael Kremer and Esther Duflo, transformed the role of science in supporting publicpolicies. It sheds light on the need to implement projects that contemplate behavioral evidence of real experiments in science. Randomized experiments, carried out through pilot studies, are, in fact, a fertile field of knowledge development in access to opportunities. In this context, in line with theoretical knowledge, I intend, in the long term, to investigate the urban dynamics related to access to opportunities in the city through living laboratories.
Data sciences,post-v erdade and dissemination of knowledge
Another issue that has instigated me is: how to spread scientific knowledge and transfer technology. In recent exchanges with international laboratories, I realized that, abroad, there is no distinction between pesquisa activities and extension as there is in Brazil. On the contrary, the dissemination of knowledge and technological transfer, in some dimension, are part of scientific research.
Still, we live in a world that produces data of all kinds in real time. We have notyet seen the full analytical potential of this data generation as tools for management and decision support, but the risks we take in relation to privacy, the induction of human behavior and, in particular, in relation to falsenews and post-truths are already evident. In this context, the dissemination of scientific knowledge becomes vital for humanity to be able to maintain some achievements, deconstruct some pre-concepts and paradigms and continue improving people's lives.
I'm in favor of themove of Open data and Open Science.  I hope that we can build algorithms not to fire fake news in real time, but to make analyses of academic production (which would be by peers, but with technological support), with more agility and responsiveness to society.
I have seen some ways to explore new possibilities:
•	The dissemination of knowledge should begin between peers. Both in the UFMG program and in the CEFET program, I feel that there is no collective understanding of what each researcher or group develops in their academic work. The most common is not to divide the classroom and not consolidate a partnership of research between peers. I want to promote academic seminars that allow the exchange of ideas, experiences, successes and frustrationsin the development of research. Initially, these seminars would be internal, but over time, we can expand to the community of CEFET-MG and, after that, open to the general public.
•	Recently I was invited to assume the role of co-tutora of the Tutorial Education Program of Administration (PET-adm). It's a very engaged and responsible team. Students are very autonomous and projects should contemplate the teaching, research and extension axes. Despite my recent transition from professor toprofessor-researcher, I think the extension has a great importance in the Brazilian context. However, we need to observe the social, local and regional demands,  so that we can effectively reduce the distances between the coletivo and individual understanding of people outside a certain field of knowledge and the specialists. I see enormous potential in PET-Adm for development and implementations that can disseminate knowledge in a more universal way and effectivelypromote technological transfer.
•	I have invested study time to seize instruments related to data science. Surprisingly, even based on more quantitative methods, I have found several paths of data use as an instrumento of reducing inequalities and promoting discussions on diversity and inclusion. Twitter has been a fantastic tool for me to explore communities around the world in their activities and get me, even if virtually, people well bacanas!
Topics to be explored
I also record here some subjects that are on the list of studies, certainly because of the constructions and transformations of renata-woman-mother-teacher-researcher-housewife-rocker-brewer-...:
•	Cities and complexidade
•	Causal inference
•	Backcasting
•	Storytelling
•	Data analysis
•	R, Python and Julia
Simply I
I have only one personal desire: put myself, at least eventually, ahead of all these delicious activities that the career as a teacherand researched now provides me and take care of myself and those I love. If I can get more balance between myself, my personal and professional life, I don't need anything else! It's as simple as that!   I want to reduce distances between all the Renata who dwell in me!
